import { Badge, Card, Grid, Group, SimpleGrid, Table, Text, Title } from '@mantine/core'
import { IconArrowUpRight, IconChartLine, IconWallet } from '@tabler/icons-react'
import MetricCard from '../components/ui/MetricCard'
import PriceChart from '../components/ui/PriceChart'
import { formatMoney } from '../utils/money'

const watchlist = [['AAPL', 'Apple Inc.', '$189.82', '+1.24%'], ['NVDA', 'NVIDIA Corp.', '$123.54', '+2.88%'], ['BTC', 'Bitcoin', '$67,280.40', '-0.62%']]
const transactions = [['Buy', 'AAPL', '12 shares', '$2,214.00'], ['Sell', 'TSLA', '5 shares', '$1,241.50'], ['Buy', 'NVDA', '8 shares', '$978.32']]
export default function Dashboard() { return <><Group justify="space-between" mb="xl"><div><Text c="dimmed" size="sm">Saturday, September 6</Text><Title order={1}>Good morning, Alex</Title></div><Badge color="violet" variant="light" size="lg">Market open in 1d 14h</Badge></Group><SimpleGrid cols={{ base: 1, sm: 2, lg: 4 }} mb="xl"><MetricCard label="Portfolio value" value={formatMoney('128450.68')} delta="+2.46%" icon={IconWallet} /><MetricCard label="Today's P/L" value="$3,084.20" delta="+2.46%" icon={IconArrowUpRight} /><MetricCard label="Buying power" value="$24,800.00" icon={IconChartLine} /><MetricCard label="Total return" value="$18,450.68" delta="+16.77%" icon={IconArrowUpRight} /></SimpleGrid><Grid><Grid.Col span={{ base: 12, lg: 8 }}><Card withBorder radius="lg" p="lg"><Group justify="space-between" mb="md"><div><Text fw={700}>Portfolio performance</Text><Text size="sm" c="dimmed">Aug 18 — Sep 6, 2025</Text></div><Badge color="teal" variant="light">+6.82%</Badge></Group><PriceChart /></Card></Grid.Col><Grid.Col span={{ base: 12, lg: 4 }}><Card withBorder radius="lg" p="lg"><Text fw={700} mb="md">Watchlist</Text>{watchlist.map(([symbol, name, price, change]) => <Group key={symbol} justify="space-between" py="sm"><div><Text fw={700}>{symbol}</Text><Text size="xs" c="dimmed">{name}</Text></div><div style={{ textAlign: 'right' }}><Text fw={600}>{price}</Text><Text size="xs" className={change.startsWith('+') ? 'positive' : 'negative'}>{change}</Text></div></Group>)}</Card></Grid.Col><Grid.Col span={12}><Card withBorder radius="lg" p="lg"><Text fw={700} mb="md">Recent activity</Text><Table><Table.Thead><Table.Tr><Table.Th>Side</Table.Th><Table.Th>Asset</Table.Th><Table.Th>Quantity</Table.Th><Table.Th ta="right">Value</Table.Th></Table.Tr></Table.Thead><Table.Tbody>{transactions.map(([side, asset, qty, value]) => <Table.Tr key={`${side}-${asset}`}><Table.Td><Badge color={side === 'Buy' ? 'teal' : 'red'} variant="light">{side}</Badge></Table.Td><Table.Td fw={700}>{asset}</Table.Td><Table.Td>{qty}</Table.Td><Table.Td ta="right">{value}</Table.Td></Table.Tr>)}</Table.Tbody></Table></Card></Grid.Col></Grid></> }
